name: Terraform Deploy
on:
    push:
      branches: [main]

 # Required for GitHub OIDC
    permissions:
      id-token: write
      contents: read
      jobs:
        deploy:
         runs-on: ubuntu-latest

         steps:
            - name: Checkout Code
              uses: actions/checkout@v4
# credentials for AWS
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
              role-to-assume: arn:aws:iam::681117450266:role/admin-role
              aws-region: us-east-1
