name: Terraform Deploy
'on':
  push:
    branches: [main]
 # Required for GitHub OIDC
permissions:
  contents: read
  id-token: write
  jobs: 
    terraform:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
       - aws-region: us-east-1
         name: Configure AWS Credentials
         role-to-assume: arn:aws:iam::681117450266:role/admin-role
         uses: aws-actions/configure-aws-credentials@v4
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3

       - name: Terraform Init
         run: terraform init

       - name: Terraform Validate
         run: terraform validate

       - name: Terraform Plan
         run: terraform plan -out=tfplan

       - name: Terraform Apply
         run: terraform apply -auto-approve tfplan
